---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'

Conditions:
  HasNot: !Equals [ 'true', 'false' ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: HasNot

Outputs:
  TestOutput:
    Value: !Ref 'AWS::StackName'
